# Generated by Django 4.2.7 on 2023-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(),
        ),
    ]
